### ISSUE TITLE
Config.php or Config_extensions.php to make imap work

### ISSUE THREAD

**Issue by wspivak** [bramley/phplist-plugin-imap#1]
Hi,

Downloaded the php-imap program but you don't say how to execute it in the config or config_extension files.

Any help would be apprecaited.

Wayne

**Comment by bramley** [comment]
You  mean this plugin? It is not called "the php-imap" program.

There is no configuration after enabling it. But if your php configuration already includes imap then this plugin is not needed.

**Comment by wspivak** [comment]
Thank you for responding.

I'm trying to get the bounce-processing to read my imap setup.  All email sits in /home/[user]/Maildir

Thanks
